---
- name: Check if use_pty is already set
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: ^[\s]*Defaults(\s*)(.*)\blogfile\b(.*)$
    state: absent
  become: true
  check_mode: true
  changed_when: false
  register: reg_check_logfile_occurrence

- name: Ensure logfile is enabled with the appropriate value in /etc/sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: ^[\s]*Defaults(\s*)(.*)\blogfile=[-]?[\w/\.]+\b(.*)$
    backrefs: true
    line: Defaults\1\2logfile={{ var_sudo_logfile }}\3
    state: present
    owner: root
    group: root
    mode: '0440'
    validate: /usr/sbin/visudo -cf %s
  become: true
  when: reg_check_logfile_occurrence['found'] >= 1

- name: Enable logfile option with appropriate value in /etc/sudoers
  lineinfile:
    path: /etc/sudoers
    line: Defaults logfile={{ var_sudo_logfile }}
    state: present
    owner: root
    group: root
    mode: '0440'
    validate: /usr/sbin/visudo -cf %s
  become: true
  when: reg_check_logfile_occurrence['found'] == 0
