---
- name: Ensure sudo package is installed
  ansible.builtin.package:
    name: sudo
    state: present
  become: true

- name: Ensure use_pty is enabled in /etc/sudoers for {{ ansible_facts['os_family'] }} based
    systems
  ansible.builtin.include_tasks:
    file: "{{ ansible_facts['os_family'] }}-use_pty.yml"
  when:
    - ansible_facts['os_family'] in ["Debian"]

- name: Include tasks to ensure the logfile option is properly set inside /etc/sudoers for
    {{ ansible_facts['os_family'] }} based systems
  ansible.builtin.include_tasks:
    file: "{{ ansible_facts['os_family'] }}-logfile.yml"
  when:
    - ansible_facts['os_family'] in ["Debian"]
