---
- name: Ensure sudo package is installed
  ansible.builtin.package:
    name: sudo
    state: present
  become: true

- name: Ensure use_pty is enabled in /etc/sudoers
  ansible.builtin.include_tasks:
    file: use_pty.yml

- name: Include tasks to ensure the logfile option is properly set inside /etc/sudoers
  ansible.builtin.include_tasks:
    file: logfile.yml
