---
- name: Check if use_pty is already set
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: ^[\s]*Defaults(.*)\buse_pty\b(.*)$
    state: absent
  become: true
  check_mode: true
  changed_when: false
  register: reg_check_pty_occurrence

- name: Ensure use_pty is enabled in /etc/sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: Defaults use_pty
    state: present
    owner: root
    group: root
    mode: '0440'
    validate: /usr/sbin/visudo -cf %s
  become: true
  when: reg_check_pty_occurrence['found'] == 0
